// Design tokens copied verbatim from the Stitch export's generated Tailwind
// config (docs/design/stitch-export/*/code.html) so the real app matches the
// approved mockups pixel-for-pixel. Do not hand-tune these values — if a
// token needs to change, it must change in the design source first.
//
// Note: borderRadius here follows the *code.html* config, which differs
// slightly from the `rounded` scale documented in
// docs/design/stitch-export/gain_trading_terminal/DESIGN.md (sm/md/lg/xl
// text). code.html is what actually produced the approved screen.png
// screenshots, so it is treated as ground truth for implementation.
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#181c24',
        'secondary-fixed-dim': '#7bd0ff',
        'on-background': '#dfe2ee',
        secondary: '#7bd0ff',
        'on-secondary-container': '#00374d',
        'primary-container': '#3198dc',
        'surface-dim': '#0f131c',
        'tertiary-container': '#7c87f3',
        surface: '#0f131c',
        'surface-bright': '#353942',
        'on-secondary-fixed-variant': '#004c69',
        'surface-container-high': '#262a33',
        'on-primary-fixed-variant': '#004b73',
        'on-primary-container': '#002c47',
        'on-primary-fixed': '#001d31',
        error: '#ffb4ab',
        'outline-variant': '#3f4850',
        'on-error-container': '#ffdad6',
        'on-primary': '#003351',
        'on-tertiary': '#131e8c',
        'primary-fixed-dim': '#93ccff',
        'on-tertiary-fixed-variant': '#2f3aa3',
        'inverse-on-surface': '#2c3039',
        'on-surface-variant': '#bfc7d2',
        'tertiary-fixed': '#e0e0ff',
        'surface-container-highest': '#31353e',
        outline: '#89929b',
        'secondary-container': '#00a6e0',
        tertiary: '#bdc2ff',
        'on-error': '#690005',
        'on-secondary': '#00354a',
        'on-surface': '#dfe2ee',
        'inverse-surface': '#dfe2ee',
        'error-container': '#93000a',
        'secondary-fixed': '#c4e7ff',
        'on-tertiary-fixed': '#000767',
        background: '#0f131c',
        'tertiary-fixed-dim': '#bdc2ff',
        'surface-container-lowest': '#0a0e16',
        primary: '#93ccff',
        'surface-tint': '#93ccff',
        'inverse-primary': '#006398',
        'on-tertiary-container': '#081486',
        'on-secondary-fixed': '#001e2c',
        'surface-container': '#1c2028',
        'surface-variant': '#31353e',
        'primary-fixed': '#cce5ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xl': '2.25rem',
        'margin-mobile': '0.75rem',
        'space-sm': '0.5rem',
        gutter: '1rem',
        'space-md': '1rem',
        'space-xs': '0.25rem',
        'space-lg': '1.5rem',
        'gutter-dense': '0.5rem',
        margin: '1.5rem',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'ticker-lg': ['JetBrains Mono'],
        'headline-md': ['Inter'],
        'label-caps': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-xl': ['Inter'],
        'headline-xl-mobile': ['Inter'],
        'body-md': ['Inter'],
        'ticker-xl': ['JetBrains Mono'],
        'headline-lg': ['Inter'],
        'ticker-sm': ['JetBrains Mono'],
        'body-sm': ['Inter'],
        'ticker-md': ['JetBrains Mono'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'ticker-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '14px', fontWeight: '600' }],
        'headline-lg-mobile': ['22px', { lineHeight: '30px', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'ticker-xl': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', fontWeight: '600' }],
        'ticker-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'ticker-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
